[config]
schemaVersion = "0.0.1"

[package]
namespace = "OMNOMNOM"
name = "OmnomnomModpack"
versionNumber = "0.0.6"
description = "A modpack for 'Omnomnom' server"
websiteUrl = "https://github.com/MLNW/valheim-modpack-omnomnom"
containsNsfwContent = false

[package.dependencies]
Amar1729-BetterLadders = "0.2.0"
Azumatt-AAA_Crafting = "1.3.4"
Azumatt-AzuClock = "1.0.2"
Azumatt-Where_You_At = "1.0.9"
BetterUI_ForeverMaintained-BetterUI_ForeverMaintained = "2.5.4"
ComfyMods-ComfyQuickSlots = "1.5.0"
Debug-Craft_Build_Smelt_Cook_Fuel_Pull_From_Containers = "3.5.0"
denikson-BepInExPack_Valheim = "5.4.2202"
Digitalroot-Digitalroots_Slope_Combat_Assistance = "2.0.21"
Goldenrevolver-Quick_Stack_Store_Sort_Trash_Restock = "1.4.5"
LVH-IT-UseEquipmentInWater = "0.2.4"
MathiasDecrock-Snap_Points_Made_Easy = "1.3.3"
Smoothbrain-Farming = "2.1.12"
Smoothbrain-Foraging = "1.0.8"
# TODO: Disallows destroying small things
#   https://github.com/blaxxun-boop/Lumberjacking/issues/6
#Smoothbrain-Lumberjacking = "1.0.5"
Smoothbrain-Mining = "1.1.5"
Smoothbrain-Ranching = "1.1.3"
Smoothbrain-Sailing = "1.1.7"
ValheimModding-Jotunn = "2.15.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./config"
target = "./config"

[publish]
repository = "https://thunderstore.io"
communities = ["valheim"]

[publish.categories]
valheim = ["modpacks"]
